### ISSUE TITLE
Editing expense in detail mode leads to exception

### ISSUE THREAD

**Issue by eknoes** [PedroCarrillo/Expense-Tracker-App#11]
When I try to edit an expense in the expense detail view, I get the following exception:

```
01-08 12:32:57.335 16432-16432/com.pedrocarrillo.expensetracker E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: com.pedrocarrillo.expensetracker, PID: 16432
                                                                                  java.lang.IllegalStateException: Fragment NewExpenseFragment{a0b3326 #0 EDIT_EXPENSE} declared target fragment ExpenseDetailFragment{5be8b67 #0 id=0x7f0f0090 ExpenseDetailFragment} that does not belong to this FragmentManager!
                                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1352)
                                                                                      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
                                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
                                                                                      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
                                                                                      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
                                                                                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
                                                                                      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                                                                                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
                                                                                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
                                                                                      at android.os.Handler.handleCallback(Handler.java:751)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at android.os.Looper.loop(Looper.java:241)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6274)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

The error is in the [onEditExpense](https://github.com/PedroCarrillo/Expense-Tracker-App/blob/99bde937bea45a52943b05349f849ca706ee16ce/ExpenseTracker/app/src/main/java/com/pedrocarrillo/expensetracker/ui/expenses/ExpenseDetailFragment.java#L87) method of ExpenseDetailFragment.

**Comment by PedroCarrillo** [comment]
Thanks for the report. I've met this bug before and thought I fix it. This is the only way to reproduce this bug right? Before I was seeing it while creating an expense. Will take a look

**Comment by eknoes** [comment]
It is the only way I figured out to meet the bug ;) Thanks!
